config/routes.rb
SampleApp::Application.routes.draw do
  resources :members do
    resources :memberships, only: [:new, :create, :edit, :update ]
    get 'dashboard', on: :collection
  end

  resources :users, only: [:edit, :update]


  resources :sessions, only: [:new, :create, :destroy]

  root to: 'sessions#new'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/copyrights', to: 'static_pages#copyrights', via: 'get'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  scope :active_on, ->(date) { where('start <= ? and (end IS NULL or ? <= end)', date, date)}
  scope :active, -> { active_on(Date.today)}
  scope :type, -> (type) { joins(:membership_type).where(membership_types: { name: type})}

  # TODO invert sense of membership.checklist_items

  after_create :add_checklist_items

  belongs_to :membership_type
  belongs_to :member
  has_and_belongs_to_many :discounts
  has_and_belongs_to_many :checklist_items

  validates :membership_type, presence: true
  validates :start, presence: true

  def invoice_date_for(year, month)
    Date.new(year, month, self.start.day)
  end

  def invoiceable_on?(year, month)
    member_on?(invoice_date_for(year, month))
  end

  def member_on?(date)
    return false if date < self.start
    return false if !self.end.nil? && date > self.end
    true
  end

  def incomplete_checklist_items
    ChecklistItem.all - checklist_items
  end

  def complete?
    incomplete_checklist_items.empty?
  end

  def total_fraction
    discounts.map {|d| d.fraction}.reduce(1,:*)
  end

  def total_discount
    (1 - total_fraction) * 100
  end

  def cost
    membership_type.monthlycost
  end

  def invoice_for(year, month)
    invoice_date = invoice_date_for(year, month)

    # GnuCash invoice has 22 fields

    id = "#{member.gnucash_id}-#{invoice_date.strftime('%y%m')}" # invoice id #
    date_opened = Date.today().to_s()
    owner_id = member.gnucash_id
    billingid = ""
    discount_list = discounts.map{|d| "#{d.percent}% #{d.name}"}.join(' and ' )
    notes = discounts.any? ? "#{discount_list} #{'discount'.pluralize(discounts.count)} applied" : ""
    date = invoice_date.to_s
    desc = "#{self.membership_type.name} membership for #{date}"
    action = ""
    account = "Income:Membership Dues"
    quantity = "1"
    price =  "%.2f" % (cost*total_fraction).round(2)  # self.cost.to_s()
    disc_type = "%"
    disc_how = ""
    discount = "0" # self.total_discount
    taxable = ""
    taxincluded = ""
    tax_table = ""
    date_posted = invoice_date.to_s()
    due_date = (invoice_date + 7).to_s()
    account_posted = "Assets:Accounts Receivable"
    memo_posted = ""
    accu_splits = ""

    [id,date_opened, owner_id, billingid, notes, date,
      desc, action, account, quantity, price, disc_type,
      disc_how, discount, taxable, taxincluded, tax_table, date_posted,
      due_date, account_posted, memo_posted, accu_splits
    ].join(',')
  end

  def enforce_at_most_one_open_membership_for_member
    new_end_date = self.start.prev_day unless self.start.nil?

    if !self.member.nil?
      self.member.memberships.each do |m|
        if m.id != self.id && m.end.nil?
          m.update_attributes(end: new_end_date)
          m.save!
        end
      end
    end
  end

  def member=(the_member)
    self.member_id = the_member.id unless the_member.nil?
    self.enforce_at_most_one_open_membership_for_member
  end

  def add_checklist_items
    self.checklist_items = ChecklistItem.all
    self.save
  end
end

app/models/membership_type.rb
class MembershipType < ActiveRecord::Base

  before_destroy :ensure_unused

  has_many :memberships
  
  validates :name, presence: true
  validates :monthlycost, presence: true

  def ensure_unused
    memberships.empty?
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :admin_user
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  def new
    @member = Member.find_by_id(params[:member])
    @membership = @member.memberships.build()
  end

  def create
 #   params[:memberships][:discount_ids] ||= []
 #   params[:memberships][:checklist_item_ids] ||= []

    p = params.require(:membership).permit(:member_id, :membership_type_id,
      :paypal, :start, :end, discount_ids: [], checklist_item_ids: [])

    @member = Member.find_by_id(p[:member_id])
    @membership = @member.memberships.new(p)
    @membership.update_attributes p
    if @membership.save

      @member.memberships.each do |m|
        if m.id != @membership.id && m.end.nil?
          m.end = @membership.start - 1.day
        end
      end

      flash[:success] = "New membership create for #{@member.name}"
      redirect_to @member
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    p = params.require(:membership).permit(:membership_type_id, :paypal, :start, :end,
      discount_ids: [], checklist_item_ids: [])
    @membership = Membership.find(params[:id])
    if @membership.update_attributes(p)
      flash[:success] = 'Membership updated'
      redirect_to @membership.member
    else
      render 'edit'
    end
  end

  def show_invoices

  end

  private

  def set_membership
    @membership = Membership.find(params[:id])
  end

end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= render 'shared/error_messages', f: f %>

<%= f.input :member_id, as: :hidden %>
<%= f.input :membership_type, include_blank: false %>
<%= f.input :paypal %>
<%= f.input :start, as: :date_picker %>
<%= f.input :end, as: :date_picker %>
<%= f.input :discounts, as: :check_boxes %>
<%= f.input :checklist_items, as: :check_boxes %>

app/views/memberships/_membership.html.erb
<li>
  <%= membership.membership_type.name %>
  Member
  <% if membership.end.nil? %>
    since 
    <%= membership.start.to_s %>
  <% else %>
    from <%= membership.start.to_s %>
    until <%= membership.end.to_s %>
  <% end %>

  <% if !membership.complete? %>
  <%= membership.incomplete_checklist_items.count %> incomplete checklist items.
  <% end %>

  <% if !current_user.nil? && current_user.admin? %>
    <%= link_to "Edit", edit_membership_path(membership) %>
  <% end %>
  <br />
</li>

app/views/memberships/edit.html.erb
<% provide(:title, 'Add Membership') %>

<h1>Change Membership for <%= @membership.member.name %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= semantic_form_for @membership do |f| %>
      <%= render 'form', f: f %>
      <%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/memberships/new.html.erb
<% provide(:title, 'Add Membership') %>

<h1>Add Membership for <%= @member.name %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= semantic_form_for @membership do |f| %>
      <%= render 'form', f: f %>
      <%= f.submit "Save Membership", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/memberships/show_invoices.html.erb
blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah 