config/routes.rb
SampleApp::Application.routes.draw do
  resources :members do
    resources :memberships, only: [:new, :create, :edit, :update ]
    get 'dashboard', on: :collection
  end

  resources :users, only: [:edit, :update]


  resources :sessions, only: [:new, :create, :destroy]

  root to: 'sessions#new'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/copyrights', to: 'static_pages#copyrights', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer navbar navbar-default">
  <div class="container">
    <big class='navbar-text'>
      Ithaca Generator Memberships
    </big>
    <div class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
	<li><a href="http://ithacagenerator.org/">Ithaca Generator</a></li>
      </ul>

    </div>
  </div>
</footer>

             

app/views/layouts/_header.html.erb
<header class="navbar navbar-default" role="navigation"> 
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to image_tag('gray_brown.png',
                            alt:"Ithaca Generator",
                            height: '90',
                  ),
                  root_path, id: "logo", class: "navbar-brand navbar-left" %>
    </div>
    <div class="nav navbar-nav navbar-right">
      <ul class="nav navbar-nav">
        <% if signed_in? %>
            <li><%= link_to "List Members", members_path %></li>
            <li><a href="/members/new">Add Member</a>

            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle"
                 data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li class="divider"></li>
                <li>
                  <%= link_to 'Change Password', edit_user_path(current_user) %>
                </li>
                <li>
                  <%= link_to "Sign out", signout_path, method:
                          "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http"//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="maincontent">
    <div class="container-fluid">
    <%= render 'static_pages/top' %>

      <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
          <%= render 'static_pages/bottom' %>

    </div>
    </div>
      <%= debug(params) if Rails.env.development? %>
      <%= render 'layouts/footer' %>
  </body>
</html>