config/routes.rb
SampleApp::Application.routes.draw do
  resources :members do
    resources :memberships, only: [:new, :create, :edit, :update ]
    get 'dashboard', on: :collection
  end

  resources :users, only: [:edit, :update]


  resources :sessions, only: [:new, :create, :destroy]

  root to: 'sessions#new'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/copyrights', to: 'static_pages#copyrights', via: 'get'

end

app/models/member.rb
class Member < ActiveRecord::Base
  # scopes
  scope :active, -> (active = true ){ joins(:memberships).merge(Membership.active) if active.present? }
  scope :type, -> (type) { joins(:memberships).merge(Membership.type(type)) if type.present? }
  scope :checklist, ->(item) { select{|m| m.current_membership && !m.current_membership.checklist_items.include?(item) } if item.present? }

  # action filters
  before_save {self.email = email.downcase }

  # relationships
  has_many :memberships
  has_one :user
  has_and_belongs_to_many :interests


  # validations
  validates :fname, presence: true, length: {maximum: 50 }
  validates :lname, presence: true, length: {maximum: 50 }
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :phone, presence: true
  validates_uniqueness_of :gnucash_id, allow_blank: true, case_sensitive: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  # Alternate accessors

  def name
    "#{self.fname} #{self.lname}"
  end

  def current_membership
    active = self.memberships.select { |m| m.member_on?(Date.today())}
    active.first if active.any?
  end

  def membership_end_date
      if current_membership
        current_membership.end_date
      else
        nil
      end
  end

  def membership_date
      if current_membership
        current_membership.start_date
      else
        nil
      end
  end

  def membership_type
    current_membership.membership_type if current_member?
  end

  def type_name
    membership_type.name if membership_type
  end

  def cost
    current_membership.cost if current_member?
  end

  def total_discount
    current_membership.total_discount if current_member?
  end

  def current_member?
    !current_membership.nil?
  end

  def member_on?(date)
    memberships.any? { |m| m.member_on?(date) }
  end

  def invoice_for(year,month)
    active_memberships = self.memberships.select { |m| m.invoiceable_on?(year, month)}

    return "Multiple Memberships for #{self.gnucash_id}" if active_memberships.count > 1
    return if !active_memberships.any?

    membership = active_memberships.first()
    membership.invoice_for(year,month)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member,     only: [:edit, :update, :show, :destroy]
  before_action :admin_user, only: [:dashboard]
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    if params[:active]
      @members = @members.select{|m| m.current_member?}
    end
    if params[:type]
      @members = @members.select{|m| m.type_name == params[:type]}
    end
    if params[:discount]
      @members = @members.select do |m|
        discount_names = m.current_membership.discounts.collect{|d| d.name}
        discount_names.include?(params[:discount])
      end
    end
    if params[:paypal]
      @members = @members.select do |m|
        if m.current_membership == nil
          false
        else
          if params[:paypal] == "true"
            m.current_membership.paypal?
          else # if params[:paypal] == "false"
            !m.current_membership.paypal?
          end
        end
      end
    end
    if params[:checklist]
      item = ChecklistItem.find_by_name(params[:checklist])
      if item
        @members = @members.select{|m| m.current_membership && !m.current_membership.checklist_items.include?(item) }
      end
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
      @memberships = @member.memberships
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def dashboard
    @members = Member.all
    @active = @members.select {|m| m.current_membership }
    @extra = @active.select { |m|    m.type_name == 'Extra' }
    @standard = @active.select { |m|    m.type_name == 'Standard' }
    @basic = @active.select { |m|    m.type_name == 'Basic' }
    @paypal = @active.select { |m|    m.current_membership.paypal? }
    @not_paypal = @active.select { |m|    !m.current_membership.paypal? }

    #foreach active member, we want a count of members with each discount
    @discounts =  {}
    MembershipType.all.each do |mt|
      @discounts[mt.name] = Hash.new
      Discount.all.each do |d|
        @discounts[mt.name][d.name] = @active.count do |m|
          discount_names = m.current_membership.discounts.collect { |dc| dc.name }
          m.current_membership.membership_type.name == mt.name && discount_names.include?(d.name)
        end
      end
    end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:lname, :fname, :address, :city, :state, :zip, :email, :phone, :birthdate, :parent, :gnucash_id, interest_ids: [])
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= semantic_form_for @member do |f| %>
    <%= f.inputs do %>
        <%= f.input :lname %>
        <%= f.input :fname %>
        <%= f.input :address %>
        <%= f.input :city %>
        <%= f.input :state %>
        <%= f.input :zip %>
        <%= f.input :email, as: :email %>
        <%= f.input :phone, as: :phone %>
        <%= f.input :birthdate, as: :date_picker %>
        <%= f.input :parent %>
        <%= f.input :interests, as: :check_boxes %>
        <%= f.input :gnucash_id %>
    <% end %>

    <%= f.actions do %>
        <%= f.action :submit, :as => :input %>
    <% end %>
<% end %>

app/views/members/dashboard.html.erb
<h1>Dashboard</h1>

<h2>Membership Stats</h2>
<ul>
  <li>
    <%= @members.count %> <%= link_to 'Total Member'.pluralize(@members.count), members_path %> (current and former)
  </li>
  <li>
    <%= @active.count %> <%= link_to 'Active Member'.pluralize(@active.count), members_path(active: true) %>
    <ul>
      <% MembershipType.all.each do |type| %>
          <li>
            <%= @active.count {|m| m.membership_type == type } %> <%= link_to type.name, members_path(type: type.name) %>
          </li>
					<ul>
            <% Discount.all.each do |discount| %>
              <% if @discounts[type.name][discount.name] != 0 %>
              <li>
                <%= @discounts[type.name][discount.name] %> <%= link_to discount.name, members_path(type: type.name, discount: discount.name) %>
              </li>
              <% end %>
            <% end %>
					</ul>
      <% end %>
    </ul>
  </li>
  <li>
    <%= @paypal.count %>  <%= link_to "using PayPal", members_path(paypal: true) %>
  </li>
  <li>
    <%= @not_paypal.count %>  <%= link_to "not using PayPal", members_path(paypal: false) %>
  </li>
</ul>

<h2>Checklist Items</h2>
<ul>
  <% ChecklistItem.all.each do |item| %>
      <li>
        <%= @active.count {|m| ! m.current_membership.checklist_items.include?(item)} %> need <%= link_to item.name, members_path(checklist: item.name) %>
      </li>
  <% end %>
</ul>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Lname</th>
      <th>Fname</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Email</th>
      <th>Phone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td>
          <% if member.memberships.any? { |m| !m.complete? } %>
              *
          <% end %>
          <%= member.lname %></td>
        <td><%= member.fname %></td>
        <td><%= member.address %></td>
        <td><%= member.city %></td>
        <td><%= member.state %></td>
        <td><%= member.zip %></td>
        <td><%= member.email %></td>
        <td><%= member.phone %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td>
          <% if member.user != current_user %>
              <%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lname:</strong>
  <%= @member.lname %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @member.fname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @member.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @member.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @member.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @member.zip %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @member.phone %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @member.birthdate %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @member.parent %>
</p>

<p>
  <strong>Interests:</strong>
  <%= @member.interests.map { |i| i.name}.join(', ') %>
</p>

<% if @member.memberships.any?  %>
      <ul class="memberships">
	<%= render @memberships %>
      </ul>
    <% end %>
    <% if current_user && current_user.admin? %>
      <%= link_to "Add Membership", new_membership_path(member: @member) %>
      <br/>
      <%= @member.invoice_for(2014,7) %>
    <% end %>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>